/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ConceptsConceptIdRouteImport } from './routes/concepts.$conceptId'
import { Route as CurriculumModuleIdRouteImport } from './routes/curriculum_.$moduleId'
import { Route as LearnChapterIdRouteImport } from './routes/learn.$chapterId'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects_.$projectId'
import { Route as PracticeAlgorithmsProblemIdRouteImport } from './routes/practice_.algorithms.$problemId'
import { Route as PracticeRustExerciseIdRouteImport } from './routes/practice_.rust.$exerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsConceptIdRoute = ConceptsConceptIdRouteImport.update({
  id: '/concepts/$conceptId',
  path: '/concepts/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumModuleIdRoute = CurriculumModuleIdRouteImport.update({
  id: '/curriculum_/$moduleId',
  path: '/curriculum/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnChapterIdRoute = LearnChapterIdRouteImport.update({
  id: '/learn/$chapterId',
  path: '/learn/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAlgorithmsProblemIdRoute =
  PracticeAlgorithmsProblemIdRouteImport.update({
    id: '/practice_/algorithms/$problemId',
    path: '/practice/algorithms/$problemId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeRustExerciseIdRoute = PracticeRustExerciseIdRouteImport.update({
  id: '/practice_/rust/$exerciseId',
  path: '/practice/rust/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/errors': typeof ErrorsRoute
  '/exam': typeof ExamRoute
  '/graph': typeof GraphRoute
  '/journal': typeof JournalRoute
  '/labs': typeof LabsRoute
  '/library': typeof LibraryRoute
  '/practice': typeof PracticeRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute
  '/curriculum/$moduleId': typeof CurriculumModuleIdRoute
  '/learn/$chapterId': typeof LearnChapterIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/practice/algorithms/$problemId': typeof PracticeAlgorithmsProblemIdRoute
  '/practice/rust/$exerciseId': typeof PracticeRustExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/errors': typeof ErrorsRoute
  '/exam': typeof ExamRoute
  '/graph': typeof GraphRoute
  '/journal': typeof JournalRoute
  '/labs': typeof LabsRoute
  '/library': typeof LibraryRoute
  '/practice': typeof PracticeRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute
  '/curriculum/$moduleId': typeof CurriculumModuleIdRoute
  '/learn/$chapterId': typeof LearnChapterIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/practice/algorithms/$problemId': typeof PracticeAlgorithmsProblemIdRoute
  '/practice/rust/$exerciseId': typeof PracticeRustExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/errors': typeof ErrorsRoute
  '/exam': typeof ExamRoute
  '/graph': typeof GraphRoute
  '/journal': typeof JournalRoute
  '/labs': typeof LabsRoute
  '/library': typeof LibraryRoute
  '/practice': typeof PracticeRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute
  '/curriculum_/$moduleId': typeof CurriculumModuleIdRoute
  '/learn/$chapterId': typeof LearnChapterIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/projects_/$projectId': typeof ProjectsProjectIdRoute
  '/practice_/algorithms/$problemId': typeof PracticeAlgorithmsProblemIdRoute
  '/practice_/rust/$exerciseId': typeof PracticeRustExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/curriculum'
    | '/dashboard'
    | '/diagnostic'
    | '/errors'
    | '/exam'
    | '/graph'
    | '/journal'
    | '/labs'
    | '/library'
    | '/practice'
    | '/projects'
    | '/review'
    | '/search'
    | '/settings'
    | '/concepts/$conceptId'
    | '/curriculum/$moduleId'
    | '/learn/$chapterId'
    | '/lessons/$lessonId'
    | '/projects/$projectId'
    | '/practice/algorithms/$problemId'
    | '/practice/rust/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/curriculum'
    | '/dashboard'
    | '/diagnostic'
    | '/errors'
    | '/exam'
    | '/graph'
    | '/journal'
    | '/labs'
    | '/library'
    | '/practice'
    | '/projects'
    | '/review'
    | '/search'
    | '/settings'
    | '/concepts/$conceptId'
    | '/curriculum/$moduleId'
    | '/learn/$chapterId'
    | '/lessons/$lessonId'
    | '/projects/$projectId'
    | '/practice/algorithms/$problemId'
    | '/practice/rust/$exerciseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/curriculum'
    | '/dashboard'
    | '/diagnostic'
    | '/errors'
    | '/exam'
    | '/graph'
    | '/journal'
    | '/labs'
    | '/library'
    | '/practice'
    | '/projects'
    | '/review'
    | '/search'
    | '/settings'
    | '/concepts/$conceptId'
    | '/curriculum_/$moduleId'
    | '/learn/$chapterId'
    | '/lessons/$lessonId'
    | '/projects_/$projectId'
    | '/practice_/algorithms/$problemId'
    | '/practice_/rust/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CurriculumRoute: typeof CurriculumRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticRoute: typeof DiagnosticRoute
  ErrorsRoute: typeof ErrorsRoute
  ExamRoute: typeof ExamRoute
  GraphRoute: typeof GraphRoute
  JournalRoute: typeof JournalRoute
  LabsRoute: typeof LabsRoute
  LibraryRoute: typeof LibraryRoute
  PracticeRoute: typeof PracticeRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewRoute: typeof ReviewRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ConceptsConceptIdRoute: typeof ConceptsConceptIdRoute
  CurriculumModuleIdRoute: typeof CurriculumModuleIdRoute
  LearnChapterIdRoute: typeof LearnChapterIdRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  PracticeAlgorithmsProblemIdRoute: typeof PracticeAlgorithmsProblemIdRoute
  PracticeRustExerciseIdRoute: typeof PracticeRustExerciseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/$conceptId': {
      id: '/concepts/$conceptId'
      path: '/concepts/$conceptId'
      fullPath: '/concepts/$conceptId'
      preLoaderRoute: typeof ConceptsConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum_/$moduleId': {
      id: '/curriculum_/$moduleId'
      path: '/curriculum/$moduleId'
      fullPath: '/curriculum/$moduleId'
      preLoaderRoute: typeof CurriculumModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$chapterId': {
      id: '/learn/$chapterId'
      path: '/learn/$chapterId'
      fullPath: '/learn/$chapterId'
      preLoaderRoute: typeof LearnChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId': {
      id: '/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice_/algorithms/$problemId': {
      id: '/practice_/algorithms/$problemId'
      path: '/practice/algorithms/$problemId'
      fullPath: '/practice/algorithms/$problemId'
      preLoaderRoute: typeof PracticeAlgorithmsProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice_/rust/$exerciseId': {
      id: '/practice_/rust/$exerciseId'
      path: '/practice/rust/$exerciseId'
      fullPath: '/practice/rust/$exerciseId'
      preLoaderRoute: typeof PracticeRustExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CurriculumRoute: CurriculumRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticRoute: DiagnosticRoute,
  ErrorsRoute: ErrorsRoute,
  ExamRoute: ExamRoute,
  GraphRoute: GraphRoute,
  JournalRoute: JournalRoute,
  LabsRoute: LabsRoute,
  LibraryRoute: LibraryRoute,
  PracticeRoute: PracticeRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewRoute: ReviewRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ConceptsConceptIdRoute: ConceptsConceptIdRoute,
  CurriculumModuleIdRoute: CurriculumModuleIdRoute,
  LearnChapterIdRoute: LearnChapterIdRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  PracticeAlgorithmsProblemIdRoute: PracticeAlgorithmsProblemIdRoute,
  PracticeRustExerciseIdRoute: PracticeRustExerciseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
