// Reference library: the curated set of openly licensed Rust books, references,
// and exercise repositories this tutor points learners at.
//
// Nothing here republishes upstream prose. Each entry stores identity, license,
// and a stable deep link, plus locally authored "why read this now" guidance.
// That keeps the content contract (see docs/contributing/content-license-checklist.md)
// at "link-only" for every third-party work in this file.

/** @typedef {{id:string,title:string,author:string,url:string,repo?:string,license:string,use:"link-only",kind:string,level:"foundation"|"intermediate"|"advanced"|"reference"|"practice",blurb:string,topics?:string[]}} LibraryEntry */

/** @type {LibraryEntry[]} */
const coreLibraries = [
  {
    id: "LIB-BOOK",
    title: "The Rust Programming Language",
    author: "The Rust Project Developers",
    url: "https://doc.rust-lang.org/book/",
    repo: "https://github.com/rust-lang/book",
    license: "MIT OR Apache-2.0",
    use: "link-only",
    kind: "book",
    level: "foundation",
    blurb:
      "The canonical guided tour. This curriculum follows its chapter order so every module has an authoritative long-form counterpart.",
  },
  {
    id: "LIB-RBE",
    title: "Rust by Example",
    author: "The Rust Project Developers",
    url: "https://doc.rust-lang.org/rust-by-example/",
    repo: "https://github.com/rust-lang/rust-by-example",
    license: "MIT OR Apache-2.0",
    use: "link-only",
    kind: "book",
    level: "foundation",
    blurb:
      "Runnable snippets for the same concepts. Use it when you want to see the shape of the code before reading the argument for it.",
  },
  {
    id: "LIB-RUSTLINGS",
    title: "Rustlings",
    author: "The Rust Project Developers",
    url: "https://rustlings.rust-lang.org/",
    repo: "https://github.com/rust-lang/rustlings",
    license: "MIT",
    use: "link-only",
    kind: "exercises",
    level: "practice",
    blurb:
      "Small compiler-error-driven fixes. Closest external analogue to this app's terminal work; good for extra repetitions.",
  },
  {
    id: "LIB-STD",
    title: "The Rust Standard Library",
    author: "The Rust Project Developers",
    url: "https://doc.rust-lang.org/std/",
    license: "MIT OR Apache-2.0",
    use: "link-only",
    kind: "api",
    level: "reference",
    blurb:
      "Primary API reference. Every collection, trait, and guarantee named in a lesson is specified here first.",
  },
  {
    id: "LIB-REFERENCE",
    title: "The Rust Reference",
    author: "The Rust Project Developers",
    url: "https://doc.rust-lang.org/reference/",
    repo: "https://github.com/rust-lang/reference",
    license: "MIT OR Apache-2.0",
    use: "link-only",
    kind: "specification",
    level: "reference",
    blurb:
      "Language-level specification. Reach for it when you need the rule rather than an explanation of the rule.",
  },
  {
    id: "LIB-ERROR-INDEX",
    title: "The rustc Error Index",
    author: "The Rust Project Developers",
    url: "https://doc.rust-lang.org/error_codes/",
    license: "MIT OR Apache-2.0",
    use: "link-only",
    kind: "reference",
    level: "reference",
    blurb:
      "One page per E-code with a minimal reproduction and repair. The compiler-error nodes in the concept map link straight here.",
  },
  {
    id: "LIB-CARGO",
    title: "The Cargo Book",
    author: "The Rust Project Developers",
    url: "https://doc.rust-lang.org/cargo/",
    repo: "https://github.com/rust-lang/cargo",
    license: "MIT OR Apache-2.0",
    use: "link-only",
    kind: "tooling",
    level: "reference",
    blurb:
      "Manifest keys, profiles, workspaces, features, and publishing. The authority behind every cargo command this app runs.",
  },
  {
    id: "LIB-EDITION",
    title: "The Edition Guide",
    author: "The Rust Project Developers",
    url: "https://doc.rust-lang.org/edition-guide/",
    license: "MIT OR Apache-2.0",
    use: "link-only",
    kind: "reference",
    level: "reference",
    blurb:
      "What changed across 2015/2018/2021/2024. Read it before trusting an older blog post or Stack Overflow answer.",
  },
  {
    id: "LIB-COMPREHENSIVE",
    title: "Comprehensive Rust",
    author: "Google",
    url: "https://google.github.io/comprehensive-rust/",
    repo: "https://github.com/google/comprehensive-rust",
    license: "Apache-2.0",
    use: "link-only",
    kind: "course",
    level: "foundation",
    blurb:
      "A dense multi-day course with speaker notes, plus bare-metal, Android, and Chromium tracks the Book never covers.",
  },
  {
    id: "LIB-COOKBOOK",
    title: "The Rust Cookbook",
    author: "The Rust Project Developers",
    url: "https://rust-lang-nursery.github.io/rust-cookbook/",
    repo: "https://github.com/rust-lang-nursery/rust-cookbook",
    license: "CC0-1.0",
    use: "link-only",
    kind: "recipes",
    level: "intermediate",
    blurb:
      "Task-shaped recipes using well-known crates. Useful once you know the language and need the ecosystem's default answer.",
  },
  {
    id: "LIB-PATTERNS",
    title: "Rust Design Patterns",
    author: "rust-unofficial",
    url: "https://rust-unofficial.github.io/patterns/",
    repo: "https://github.com/rust-unofficial/patterns",
    license: "MPL-2.0",
    use: "link-only",
    kind: "book",
    level: "intermediate",
    blurb:
      "Idioms, patterns, and named anti-patterns. The vocabulary layer between 'it compiles' and 'a reviewer would accept it'.",
  },
  {
    id: "LIB-EFFECTIVE",
    title: "Effective Rust",
    author: "David Drysdale",
    url: "https://effective-rust.com/",
    license: "CC-BY-NC-ND-4.0",
    use: "link-only",
    kind: "book",
    level: "intermediate",
    blurb:
      "Thirty-five specific pieces of advice on types, traits, dependencies, and tooling. Commercially published, so this app links to it and never reproduces it.",
  },
  {
    id: "LIB-API-GUIDELINES",
    title: "Rust API Guidelines",
    author: "The Rust Library Team",
    url: "https://rust-lang.github.io/api-guidelines/",
    repo: "https://github.com/rust-lang/api-guidelines",
    license: "MIT OR Apache-2.0",
    use: "link-only",
    kind: "checklist",
    level: "intermediate",
    blurb:
      "The checklist library authors are held to: naming, interoperability, flexibility, future proofing.",
  },
  {
    id: "LIB-NOMICON",
    title: "The Rustonomicon",
    author: "The Rust Project Developers",
    url: "https://doc.rust-lang.org/nomicon/",
    repo: "https://github.com/rust-lang/nomicon",
    license: "MIT OR Apache-2.0",
    use: "link-only",
    kind: "book",
    level: "advanced",
    blurb:
      "The dark arts of unsafe Rust: aliasing, variance, drop order, and the invariants you now have to uphold by hand.",
  },
  {
    id: "LIB-TOO-MANY-LISTS",
    title: "Learn Rust With Entirely Too Many Linked Lists",
    author: "Aria Beingessner",
    url: "https://rust-unofficial.github.io/too-many-lists/",
    repo: "https://github.com/rust-unofficial/too-many-lists",
    license: "MIT",
    use: "link-only",
    kind: "book",
    level: "advanced",
    blurb:
      "The best available treatment of ownership under pressure. Work it after Chapter 15; it turns smart pointers into muscle memory.",
  },
  {
    id: "LIB-ATOMICS",
    title: "Rust Atomics and Locks",
    author: "Mara Bos",
    url: "https://mara.nl/atomics/",
    license: "CC-BY-NC-ND-4.0",
    use: "link-only",
    kind: "book",
    level: "advanced",
    blurb:
      "Free online edition covering memory ordering, building your own locks, and what the OS actually does underneath.",
  },
  {
    id: "LIB-ASYNC",
    title: "Asynchronous Programming in Rust",
    author: "The Rust Project Developers",
    url: "https://rust-lang.github.io/async-book/",
    repo: "https://github.com/rust-lang/async-book",
    license: "MIT",
    use: "link-only",
    kind: "book",
    level: "advanced",
    blurb:
      "Futures, executors, pinning, and cancellation from first principles rather than from one runtime's API surface.",
  },
  {
    id: "LIB-TOKIO",
    title: "Tokio Tutorial",
    author: "The Tokio Contributors",
    url: "https://tokio.rs/tokio/tutorial",
    repo: "https://github.com/tokio-rs/website",
    license: "MIT",
    use: "link-only",
    kind: "tutorial",
    level: "advanced",
    blurb:
      "The concrete counterpart to the async book: tasks, channels, select, shared state, and graceful shutdown in a real runtime.",
  },
  {
    id: "LIB-MACROS",
    title: "The Little Book of Rust Macros",
    author: "Veykril (community edition)",
    url: "https://veykril.github.io/tlborm/",
    repo: "https://github.com/veykril/tlborm",
    license: "MIT",
    use: "link-only",
    kind: "book",
    level: "advanced",
    blurb:
      "macro_rules! from fragment specifiers to hygiene, then the bridge into procedural macros.",
  },
  {
    id: "LIB-PERF",
    title: "The Rust Performance Book",
    author: "Nicholas Nethercote",
    url: "https://nnethercote.github.io/perf-book/",
    repo: "https://github.com/nnethercote/perf-book",
    license: "MIT OR Apache-2.0",
    use: "link-only",
    kind: "book",
    level: "advanced",
    blurb:
      "Profiling first, then measured wins: allocation, hashing, bounds checks, build configuration, and benchmarking discipline.",
  },
  {
    id: "LIB-RUST-QUIZ",
    title: "Rust Quiz",
    author: "David Tolnay",
    url: "https://dtolnay.github.io/rust-quiz/",
    repo: "https://github.com/dtolnay/rust-quiz",
    license: "CC-BY-SA-4.0",
    use: "link-only",
    kind: "quiz",
    level: "advanced",
    blurb:
      "Short programs with surprising output and a full explanation. Excellent calibration for how well you actually read Rust.",
  },
  {
    id: "LIB-ALGORITHMS",
    title: "TheAlgorithms / Rust",
    author: "TheAlgorithms community",
    url: "https://github.com/TheAlgorithms/Rust",
    repo: "https://github.com/TheAlgorithms/Rust",
    license: "MIT",
    use: "link-only",
    kind: "code",
    level: "practice",
    blurb:
      "Reference implementations for classic algorithms in idiomatic-ish Rust. Compare against your own after you have solved a pattern.",
  },
  {
    id: "LIB-EXERCISM",
    title: "Exercism Rust Track",
    author: "Exercism",
    url: "https://exercism.org/tracks/rust",
    repo: "https://github.com/exercism/rust",
    license: "MIT",
    use: "link-only",
    kind: "exercises",
    level: "practice",
    blurb:
      "Around a hundred graded exercises with published community solutions — the widest source of alternative idiom for a solved problem.",
  },
];

/**
 * The wider open Rust literature: every further free book, course, exercise
 * set, reference, tool, and public dataset the tutor points at. Rows are
 * [id, title, author, url, repo | null, license, kind, level, topics, blurb].
 * Licenses were checked against each upstream repository or site; works that
 * are free to read but not openly licensed say so rather than implying reuse.
 */
const extendedRows = [
  // ---- Official Rust project documentation ----
  [
    "LIB-LEARN-HUB",
    "Learn Rust (rust-lang.org)",
    "The Rust Project Developers",
    "https://www.rust-lang.org/learn",
    "https://github.com/rust-lang/www.rust-lang.org",
    "MIT OR Apache-2.0",
    "hub",
    "foundation",
    ["getting-started"],
    "The project's own index of official learning material. Start here to see what is canonical before trusting a third-party summary.",
  ],
  [
    "LIB-RUSTC-BOOK",
    "The rustc Book",
    "The Rust Project Developers",
    "https://doc.rust-lang.org/rustc/",
    "https://github.com/rust-lang/rust",
    "MIT OR Apache-2.0",
    "tooling",
    "reference",
    ["tooling", "lints", "targets"],
    "Compiler flags, lint levels, codegen options, and platform support. Read the lints chapter before you reach for #[allow].",
  ],
  [
    "LIB-RUSTDOC-BOOK",
    "The rustdoc Book",
    "The Rust Project Developers",
    "https://doc.rust-lang.org/rustdoc/",
    "https://github.com/rust-lang/rust",
    "MIT OR Apache-2.0",
    "tooling",
    "reference",
    ["documentation", "testing", "modules"],
    "How doc comments, intra-doc links, and doctests work. Doctests are a second test suite most beginners never switch on.",
  ],
  [
    "LIB-CLIPPY-BOOK",
    "Clippy Documentation",
    "The Rust Project Developers",
    "https://doc.rust-lang.org/clippy/",
    "https://github.com/rust-lang/rust-clippy",
    "MIT OR Apache-2.0",
    "tooling",
    "reference",
    ["tooling", "lints", "idioms"],
    "Configuring and running Clippy, lint groups, and how to justify an allow. Pairs with the searchable lint list dataset below.",
  ],
  [
    "LIB-STYLE-GUIDE",
    "The Rust Style Guide",
    "The Rust Project Developers",
    "https://doc.rust-lang.org/style-guide/",
    "https://github.com/rust-lang/rust",
    "MIT OR Apache-2.0",
    "reference",
    "reference",
    ["idioms", "tooling"],
    "The formatting rules rustfmt implements, with the reasoning. Useful when a formatting choice looks arbitrary.",
  ],
  [
    "LIB-RUSTFMT",
    "rustfmt Configuration",
    "The Rust Project Developers",
    "https://rust-lang.github.io/rustfmt/",
    "https://github.com/rust-lang/rustfmt",
    "MIT OR Apache-2.0",
    "tooling",
    "reference",
    ["tooling"],
    "Every rustfmt.toml option with before/after examples, filterable by stable versus unstable.",
  ],
  [
    "LIB-UNSTABLE-BOOK",
    "The Unstable Book",
    "The Rust Project Developers",
    "https://doc.rust-lang.org/unstable-book/",
    "https://github.com/rust-lang/rust",
    "MIT OR Apache-2.0",
    "reference",
    "advanced",
    ["nightly", "language-evolution"],
    "Nightly-only features and their tracking issues. Read it to understand where the language is going, not to build on it.",
  ],
  [
    "LIB-RFCS",
    "The Rust RFC Book",
    "The Rust Project Developers",
    "https://rust-lang.github.io/rfcs/",
    "https://github.com/rust-lang/rfcs",
    "MIT OR Apache-2.0",
    "design-history",
    "advanced",
    ["language-evolution", "design"],
    "The accepted design documents behind every major feature. An RFC's 'Motivation' and 'Alternatives' sections explain why a rule is the way it is.",
  ],
  [
    "LIB-FLS",
    "The FLS (Rust language specification)",
    "The Rust Project (originally Ferrous Systems and AdaCore)",
    "https://rust-lang.github.io/fls/",
    "https://github.com/rust-lang/fls",
    "MIT OR Apache-2.0",
    "specification",
    "reference",
    ["specification"],
    "A rigorously structured specification of Rust, maintained by the Rust project since 2025. Numbered paragraphs make it the most citable language reference.",
  ],
  [
    "LIB-UCG",
    "Unsafe Code Guidelines Reference",
    "Rust Unsafe Code Guidelines Working Group",
    "https://rust-lang.github.io/unsafe-code-guidelines/",
    "https://github.com/rust-lang/unsafe-code-guidelines",
    "MIT OR Apache-2.0",
    "specification",
    "advanced",
    ["unsafe", "memory-layout"],
    "Layout, validity, and aliasing rules that unsafe code must uphold. Read after the Rustonomicon when you need the precise invariant.",
  ],
  [
    "LIB-RUSTC-DEV-GUIDE",
    "Rust Compiler Development Guide",
    "The Rust Project Developers",
    "https://rustc-dev-guide.rust-lang.org/",
    "https://github.com/rust-lang/rustc-dev-guide",
    "MIT OR Apache-2.0",
    "book",
    "advanced",
    ["compiler-internals", "borrow-checker"],
    "How rustc is built: HIR, MIR, type checking, and the borrow checker. The MIR borrow-check chapter shows what 'the borrow checker' literally computes.",
  ],
  [
    "LIB-FORGE",
    "Rust Forge",
    "The Rust Project Developers",
    "https://forge.rust-lang.org/",
    "https://github.com/rust-lang/rust-forge",
    "MIT OR Apache-2.0",
    "community",
    "advanced",
    ["contributing", "release-process"],
    "Release trains, team structure, and contribution process. Where to go when you want to contribute to Rust itself.",
  ],
  [
    "LIB-RUST-ANALYZER",
    "rust-analyzer Manual",
    "rust-analyzer contributors",
    "https://rust-analyzer.github.io/",
    "https://github.com/rust-lang/rust-analyzer",
    "MIT OR Apache-2.0",
    "tooling",
    "reference",
    ["tooling", "editor"],
    "Editor setup, assists, and inlay hints. Inlay type hints are the fastest way to see what inference decided.",
  ],
  [
    "LIB-MIRI",
    "Miri",
    "The Rust Project Developers",
    "https://github.com/rust-lang/miri",
    "https://github.com/rust-lang/miri",
    "MIT OR Apache-2.0",
    "tooling",
    "advanced",
    ["unsafe", "undefined-behavior", "testing"],
    "An interpreter that detects undefined behaviour in tests. Run it on any crate that contains unsafe before you believe a safety comment.",
  ],
  [
    "LIB-PLAYGROUND",
    "Rust Playground",
    "The Rust Project Developers",
    "https://play.rust-lang.org/",
    "https://github.com/rust-lang/rust-playground",
    "MIT OR Apache-2.0",
    "tool",
    "practice",
    ["experimentation", "assembly", "mir"],
    "Run snippets on stable, beta, or nightly and view MIR, LLVM IR, or assembly. Also runs Clippy and Miri on a snippet.",
  ],
  [
    "LIB-GODBOLT",
    "Compiler Explorer",
    "Matt Godbolt and contributors",
    "https://godbolt.org/",
    "https://github.com/compiler-explorer/compiler-explorer",
    "BSD-2-Clause",
    "tool",
    "advanced",
    ["performance", "assembly", "zero-cost"],
    "See the machine code rustc emits side by side with source. It turns 'zero-cost abstraction' from a slogan into something you can check.",
  ],

  // ---- Free books and courses ----
  [
    "LIB-BROWN-BOOK",
    "The Rust Book: Experimental Edition (Brown University)",
    "Will Crichton, Gavin Gray, Shriram Krishnamurthi (Cognitive Engineering Lab)",
    "https://rust-book.cs.brown.edu/",
    "https://github.com/cognitive-engineering-lab/rust-book",
    "MIT OR Apache-2.0",
    "book",
    "foundation",
    ["ownership", "quizzes", "retrieval-practice"],
    "The official Book with embedded quizzes, a redesigned ownership chapter, and 'Ownership Inventory' scenarios. Its quiz data drove published research on how people learn Rust.",
  ],
  [
    "LIB-RUST-BY-PRACTICE",
    "Rust By Practice",
    "sunface and contributors",
    "https://practice.rs/",
    "https://github.com/sunface/rust-by-practice",
    "CC-BY-4.0",
    "exercises",
    "practice",
    ["exercises", "ownership", "traits", "async"],
    "Fill-in and fix-the-bug exercises organised by the same topics as the Book, with published solutions. Good for a second round after each chapter.",
  ],
  [
    "LIB-100-EXERCISES",
    "100 Exercises to Learn Rust",
    "Luca Palmieri (Mainmatter)",
    "https://rust-exercises.com/100-exercises/",
    "https://github.com/mainmatter/100-exercises-to-learn-rust",
    "CC-BY-NC-4.0",
    "course",
    "practice",
    ["exercises", "traits", "concurrency", "async"],
    "A test-driven course built around one ticketing domain. The app already embeds this pack as its Mainmatter practice track; the upstream site has the prose.",
  ],
  [
    "LIB-EASY-RUST",
    "Easy Rust",
    "Dave MacLeod",
    "https://dhghomon.github.io/easy_rust/",
    "https://github.com/Dhghomon/easy_rust",
    "MIT",
    "book",
    "foundation",
    ["getting-started", "ownership", "collections"],
    "The whole language in simple English with short examples. A good second explanation when the Book's phrasing does not land.",
  ],
  [
    "LIB-TOUR",
    "Tour of Rust",
    "Richard Anaya and contributors",
    "https://tourofrust.com/",
    "https://github.com/richardanaya/tour_of_rust",
    "MIT",
    "interactive",
    "foundation",
    ["getting-started", "syntax"],
    "Bite-sized pages each with a runnable example, translated into many languages. Fast syntax orientation before the deeper chapters.",
  ],
  [
    "LIB-GENTLE",
    "A Gentle Introduction to Rust",
    "Steve Donovan",
    "https://stevedonovan.github.io/rust-gentle-intro/",
    "https://github.com/stevedonovan/gentle-intro",
    "MIT",
    "book",
    "foundation",
    ["getting-started", "ownership", "errors"],
    "A pragmatic tour aimed at programmers from other languages, with a candid 'pain points' chapter.",
  ],
  [
    "LIB-R4CPPP",
    "Rust for C++ Programmers",
    "Nick Cameron",
    "https://github.com/nrc/r4cppp",
    "https://github.com/nrc/r4cppp",
    "MIT OR Apache-2.0",
    "book",
    "intermediate",
    ["ownership", "pointers", "smart-pointers"],
    "Maps unique_ptr, shared_ptr, and references onto Box, Rc, and borrows. Read it if you already think in C++ ownership terms.",
  ],
  [
    "LIB-CHEATS",
    "Rust Language Cheat Sheet",
    "Ralf Biedert",
    "https://cheats.rs/",
    "https://github.com/ralfbiedert/cheats.rs",
    "Code snippets CC0-1.0; prose free to read",
    "reference",
    "reference",
    ["syntax", "memory-layout", "traits"],
    "Dense one-page reference with memory-layout diagrams for String, Vec, Box, and Rc. Keep it open while doing exercises.",
  ],
  [
    "LIB-CLI-BOOK",
    "Command Line Applications in Rust",
    "Rust CLI Working Group",
    "https://rust-cli.github.io/book/",
    "https://github.com/rust-cli/book",
    "MIT",
    "book",
    "intermediate",
    ["cli", "errors", "testing", "io"],
    "A 15-minute CLI tutorial followed by chapters on argument parsing, errors, output, and testing binaries. A natural first real project after chapter 11.",
  ],
  [
    "LIB-EMBEDDED-BOOK",
    "The Embedded Rust Book",
    "Rust Embedded Working Group",
    "https://docs.rust-embedded.org/book/",
    "https://github.com/rust-embedded/book",
    "Prose CC-BY-SA-4.0; code MIT OR Apache-2.0",
    "book",
    "advanced",
    ["embedded", "no-std", "unsafe"],
    "no_std, peripherals as owned singletons, and interrupts. Shows ownership modelling hardware, not just memory.",
  ],
  [
    "LIB-DISCOVERY",
    "Discovery (micro:bit v2)",
    "Rust Embedded Working Group",
    "https://docs.rust-embedded.org/discovery-mb2/",
    "https://github.com/rust-embedded/discovery-mb2",
    "Prose CC-BY-4.0; code MIT OR Apache-2.0",
    "book",
    "intermediate",
    ["embedded", "hardware"],
    "A beginner embedded course on an inexpensive micro:bit board, from blinking an LED to serial communication.",
  ],
  [
    "LIB-EMBEDONOMICON",
    "The Embedonomicon",
    "Rust Embedded Working Group",
    "https://docs.rust-embedded.org/embedonomicon/",
    "https://github.com/rust-embedded/embedonomicon",
    "Prose CC-BY-SA-4.0; code MIT OR Apache-2.0",
    "book",
    "advanced",
    ["embedded", "linkers", "no-std"],
    "Build a no_std program from nothing: linker scripts, the reset handler, and memory layout.",
  ],
  [
    "LIB-OS-PHIL-OPP",
    "Writing an OS in Rust",
    "Philipp Oppermann",
    "https://os.phil-opp.com/",
    "https://github.com/phil-opp/blog_os",
    "Prose CC-BY-NC-4.0; code MIT OR Apache-2.0",
    "book",
    "advanced",
    ["systems", "no-std", "unsafe", "async"],
    "A step-by-step x86_64 kernel: VGA output, interrupts, paging, heap allocation, and async tasks. The best long project for unsafe and no_std.",
  ],
  [
    "LIB-WASM-BOOK",
    "Rust and WebAssembly",
    "Rust and WebAssembly Working Group (archived)",
    "https://rustwasm.github.io/docs/book/",
    "https://github.com/rustwasm/book",
    "MIT OR Apache-2.0",
    "book",
    "intermediate",
    ["webassembly", "ffi"],
    "Game of Life compiled to WebAssembly, with profiling and size optimisation. The organisation is archived, but the model of the JS/Wasm boundary still holds.",
  ],
  [
    "LIB-SERDE",
    "Serde",
    "Erick Tryzelaar, David Tolnay",
    "https://serde.rs/",
    "https://github.com/serde-rs/serde-rs.github.io",
    "MIT OR Apache-2.0",
    "book",
    "intermediate",
    ["serialization", "traits", "derive"],
    "How the de facto serialization framework uses traits and derive macros. The data-model page is a masterclass in trait design.",
  ],
  [
    "LIB-CRITERION",
    "Criterion.rs User Guide",
    "Brook Heisler and contributors",
    "https://bheisler.github.io/criterion.rs/book/",
    "https://github.com/bheisler/criterion.rs",
    "MIT OR Apache-2.0",
    "tooling",
    "advanced",
    ["performance", "benchmarking"],
    "Statistics-driven benchmarking. Pair it with the Performance Book so optimisations are measured rather than guessed.",
  ],
  [
    "LIB-FUZZ-BOOK",
    "Rust Fuzz Book",
    "rust-fuzz contributors",
    "https://rust-fuzz.github.io/book/",
    "https://github.com/rust-fuzz/book",
    "MIT OR Apache-2.0",
    "tooling",
    "advanced",
    ["testing", "fuzzing", "security"],
    "cargo-fuzz and afl.rs from first target to structure-aware fuzzing. The next step after unit and property tests.",
  ],
  [
    "LIB-MINI-REDIS",
    "mini-redis",
    "Tokio contributors",
    "https://github.com/tokio-rs/mini-redis",
    "https://github.com/tokio-rs/mini-redis",
    "MIT",
    "code",
    "advanced",
    ["async", "networking", "code-reading"],
    "An intentionally readable Redis server written to teach Tokio. Read it alongside the Tokio tutorial.",
  ],
  [
    "LIB-PROC-MACRO-WORKSHOP",
    "Procedural Macros Workshop",
    "David Tolnay",
    "https://github.com/dtolnay/proc-macro-workshop",
    "https://github.com/dtolnay/proc-macro-workshop",
    "MIT OR Apache-2.0",
    "exercises",
    "advanced",
    ["macros", "exercises"],
    "Five test-driven projects that build real derive, attribute, and function-like macros. The practical sequel to the Little Book of Rust Macros.",
  ],
  [
    "LIB-ALGO-CLUB",
    "Rust Algorithm Club",
    "Weihang Lo and contributors",
    "https://rust-algo.club/",
    "https://github.com/weihanglo/rust-algorithm-club",
    "Code MIT; articles CC-BY-NC-SA-4.0",
    "book",
    "practice",
    ["algorithms", "collections"],
    "Classic algorithms and data structures explained with Rust implementations. Useful beside the interview-practice track.",
  ],
  [
    "LIB-MS-LEARN",
    "Take your first steps with Rust (Microsoft Learn)",
    "Microsoft",
    "https://learn.microsoft.com/training/paths/rust-first-steps/",
    null,
    "Free online course (Microsoft Learn terms)",
    "course",
    "foundation",
    ["getting-started", "errors", "testing"],
    "A free guided learning path with sandboxed exercises. Another voice for the chapter 1–11 material.",
  ],

  // ---- Code worth reading ----
  [
    "LIB-RIPGREP",
    "ripgrep",
    "Andrew Gallant",
    "https://github.com/BurntSushi/ripgrep",
    "https://github.com/BurntSushi/ripgrep",
    "MIT OR Unlicense",
    "code",
    "advanced",
    ["code-reading", "cli", "performance"],
    "A production command-line tool with exemplary error handling, crate boundaries, and comments. The standard recommendation for 'show me good Rust'.",
  ],
  [
    "LIB-UUTILS",
    "uutils coreutils",
    "uutils contributors",
    "https://github.com/uutils/coreutils",
    "https://github.com/uutils/coreutils",
    "MIT",
    "code",
    "intermediate",
    ["code-reading", "cli", "io"],
    "Rust rewrites of ls, cat, wc, and friends. Each utility is small enough to read in one sitting and has a known specification.",
  ],
  [
    "LIB-STD-SOURCE",
    "The standard library source",
    "The Rust Project Developers",
    "https://github.com/rust-lang/rust/tree/main/library",
    "https://github.com/rust-lang/rust",
    "MIT OR Apache-2.0",
    "code",
    "advanced",
    ["code-reading", "unsafe", "collections"],
    "Every std doc page has a 'Source' link. Reading Vec, Option, and RefCell's implementations shows small audited unsafe wrapped in safe APIs.",
  ],
  [
    "LIB-AXUM-EXAMPLES",
    "axum examples",
    "Tokio contributors",
    "https://github.com/tokio-rs/axum/tree/main/examples",
    "https://github.com/tokio-rs/axum",
    "MIT",
    "code",
    "intermediate",
    ["web", "async", "code-reading"],
    "Dozens of small, focused web-service examples (the framework this app's own service uses).",
  ],

  // ---- Public datasets you can learn from ----
  [
    "LIB-DATA-UI-TESTS",
    "rustc UI test suite",
    "The Rust Project Developers",
    "https://github.com/rust-lang/rust/tree/main/tests/ui",
    "https://github.com/rust-lang/rust",
    "MIT OR Apache-2.0",
    "dataset",
    "advanced",
    ["dataset", "compiler-errors", "borrow-checker"],
    "Thousands of small programs paired with the exact diagnostics rustc must print. The largest corpus of 'predict the compiler error' drills in existence.",
  ],
  [
    "LIB-DATA-ERROR-CODES",
    "rustc error-code explanations (source)",
    "The Rust Project Developers",
    "https://github.com/rust-lang/rust/tree/main/compiler/rustc_error_codes/src/error_codes",
    "https://github.com/rust-lang/rust",
    "MIT OR Apache-2.0",
    "dataset",
    "reference",
    ["dataset", "compiler-errors"],
    "One Markdown file per E-code with an erroneous example and a fix: the machine-readable source behind the Error Index.",
  ],
  [
    "LIB-DATA-CLIPPY-LINTS",
    "Clippy lint list",
    "The Rust Project Developers",
    "https://rust-lang.github.io/rust-clippy/master/index.html",
    "https://github.com/rust-lang/rust-clippy",
    "MIT OR Apache-2.0",
    "dataset",
    "reference",
    ["dataset", "lints", "idioms"],
    "Over 800 lints, each with 'what it does', 'why is this bad', and a before/after example. Browse one category a week as an idiom curriculum.",
  ],
  [
    "LIB-DATA-RUSTSEC",
    "RustSec Advisory Database",
    "Rust Secure Code Working Group",
    "https://rustsec.org/advisories/",
    "https://github.com/rustsec/advisory-db",
    "CC0-1.0 (GitHub-imported advisories CC-BY-4.0)",
    "dataset",
    "advanced",
    ["dataset", "security", "unsafe"],
    "Every published vulnerability in a crates.io crate. Reading the unsafe-related advisories is a catalogue of real soundness bugs.",
  ],
  [
    "LIB-DATA-CRATES-DUMP",
    "crates.io database dump",
    "crates.io team",
    "https://crates.io/data-access",
    "https://github.com/rust-lang/crates.io",
    "Access policy CC-BY-4.0; data licences documented in the dump",
    "dataset",
    "practice",
    ["dataset", "data-engineering", "ecosystem"],
    "A daily CSV export of crate, version, and dependency metadata. A realistic dataset for your own parsing, graph, and analytics projects.",
  ],
  [
    "LIB-DATA-RUST-QUIZ-SRC",
    "Rust Quiz question sources",
    "David Tolnay",
    "https://github.com/dtolnay/rust-quiz/tree/master/questions",
    "https://github.com/dtolnay/rust-quiz",
    "CC-BY-SA-4.0",
    "dataset",
    "advanced",
    ["dataset", "quizzes", "language-edge-cases"],
    "The source of each Rust Quiz puzzle with its explanation, ready for self-study offline.",
  ],

  // ---- Ecosystem maps, news, and community ----
  [
    "LIB-AWESOME-RUST",
    "Awesome Rust",
    "rust-unofficial contributors",
    "https://github.com/rust-unofficial/awesome-rust",
    "https://github.com/rust-unofficial/awesome-rust",
    "CC0-1.0",
    "hub",
    "reference",
    ["ecosystem", "crates"],
    "The long curated list of Rust applications, libraries, and tools. Use it to find prior art before writing something.",
  ],
  [
    "LIB-AWESOME-EMBEDDED",
    "Awesome Embedded Rust",
    "Rust Embedded Working Group",
    "https://github.com/rust-embedded/awesome-embedded-rust",
    "https://github.com/rust-embedded/awesome-embedded-rust",
    "CC0-1.0",
    "hub",
    "reference",
    ["embedded", "ecosystem"],
    "HALs, board-support crates, drivers, and RTOS options, organised by chip family.",
  ],
  [
    "LIB-DOCS-RS",
    "docs.rs",
    "docs.rs team",
    "https://docs.rs/",
    "https://github.com/rust-lang/docs.rs",
    "Service; site code MIT",
    "api",
    "reference",
    ["ecosystem", "documentation"],
    "API documentation for every published crate version. Read a crate's docs before adding it as a dependency.",
  ],
  [
    "LIB-TWIR",
    "This Week in Rust",
    "This Week in Rust editors",
    "https://this-week-in-rust.org/",
    "https://github.com/rust-lang/this-week-in-rust",
    "Content CC-BY-SA; code MIT",
    "newsletter",
    "intermediate",
    ["community", "news"],
    "The weekly digest of articles, releases, and calls for participation. Skim the 'Crate of the Week' as a gentle ecosystem tour.",
  ],
  [
    "LIB-RUST-BLOG",
    "The Rust Blog",
    "The Rust Project Developers",
    "https://blog.rust-lang.org/",
    "https://github.com/rust-lang/blog.rust-lang.org",
    "MIT OR Apache-2.0",
    "newsletter",
    "intermediate",
    ["release-notes", "language-evolution"],
    "Release announcements every six weeks explain each newly stabilised feature with an example.",
  ],
  [
    "LIB-USERS-FORUM",
    "Rust Users Forum",
    "Rust community",
    "https://users.rust-lang.org/",
    null,
    "Community forum (see site terms)",
    "community",
    "foundation",
    ["community", "help"],
    "The official place to ask for help. Searching it for your exact error message usually finds a worked explanation.",
  ],

  // ---- Talks and research ----
  [
    "LIB-CRUST-OF-RUST",
    "Crust of Rust (video series)",
    "Jon Gjengset",
    "https://www.youtube.com/@jonhoo",
    null,
    "Free to watch",
    "video",
    "advanced",
    ["lifetimes", "iterators", "smart-pointers", "concurrency", "async"],
    "Long-form live coding that builds std types from scratch: iterators, smart pointers, channels, atomics. Watch after the matching chapter here.",
  ],
  [
    "LIB-RUST-VIDEOS",
    "Rust conference talks",
    "The Rust Foundation and conference organisers",
    "https://www.youtube.com/@RustVideos",
    null,
    "Free to watch",
    "video",
    "intermediate",
    ["community", "design"],
    "RustConf and other conference talks. Good for how teams use Rust in production and why features were designed as they were.",
  ],
  [
    "LIB-RESEARCH-OWNERSHIP-MODEL",
    "A Grounded Conceptual Model for Ownership Types in Rust",
    "Will Crichton, Gavin Gray, Shriram Krishnamurthi (OOPSLA 2023)",
    "https://cs.brown.edu/people/sk/Publications/Papers/Published/cgk-grounded-model-rust-ownership/paper.pdf",
    null,
    "Open-access paper",
    "research",
    "advanced",
    ["ownership", "learning-science"],
    "The research behind the Brown edition's permissions model of borrowing (read/write/own). If ownership still feels like magic, this model is the fix.",
  ],
  [
    "LIB-RESEARCH-PROFILING",
    "Profiling Programming Language Learning",
    "Will Crichton, Shriram Krishnamurthi (OOPSLA 2024)",
    "https://cel.cs.brown.edu/paper/profiling-pl-learning/",
    null,
    "Open-access paper",
    "research",
    "advanced",
    ["learning-science", "quizzes"],
    "What 1.1 million quiz answers revealed about where Rust learners struggle, and which interventions helped. It shaped this app's question design.",
  ],
  [
    "LIB-RESEARCH-RUSTBELT",
    "RustBelt: Securing the Foundations of Rust",
    "Ralf Jung, Jacques-Henri Jourdan, Robbert Krebbers, Derek Dreyer (POPL 2018)",
    "https://plv.mpi-sws.org/rustbelt/popl18/",
    null,
    "Open-access paper",
    "research",
    "advanced",
    ["unsafe", "formal-methods"],
    "A machine-checked proof that safe Rust plus correctly encapsulated unsafe code is memory safe. The theory behind 'wrap unsafe in a safe API'.",
  ],
];

const extendedLibraries = extendedRows.map(
  ([id, title, author, url, repo, license, kind, level, topics, blurb]) => ({
    id,
    title,
    author,
    url,
    ...(repo ? { repo } : {}),
    license,
    use: "link-only",
    kind,
    level,
    topics,
    blurb,
  }),
);

/** Topic tags for the core entries, so every work in the library is filterable. */
const coreTopics = {
  "LIB-BOOK": ["getting-started", "ownership", "traits", "concurrency"],
  "LIB-RBE": ["getting-started", "syntax", "examples"],
  "LIB-RUSTLINGS": ["exercises", "compiler-errors"],
  "LIB-STD": ["api", "collections"],
  "LIB-REFERENCE": ["specification"],
  "LIB-ERROR-INDEX": ["compiler-errors"],
  "LIB-CARGO": ["tooling", "modules", "testing"],
  "LIB-EDITION": ["language-evolution"],
  "LIB-COMPREHENSIVE": ["getting-started", "ownership", "concurrency", "unsafe"],
  "LIB-COOKBOOK": ["recipes", "ecosystem"],
  "LIB-PATTERNS": ["idioms", "design"],
  "LIB-EFFECTIVE": ["idioms", "traits", "design"],
  "LIB-API-GUIDELINES": ["idioms", "design"],
  "LIB-NOMICON": ["unsafe", "memory-layout"],
  "LIB-TOO-MANY-LISTS": ["smart-pointers", "unsafe", "ownership"],
  "LIB-ATOMICS": ["concurrency", "atomics"],
  "LIB-ASYNC": ["async"],
  "LIB-TOKIO": ["async", "networking"],
  "LIB-MACROS": ["macros"],
  "LIB-PERF": ["performance"],
  "LIB-RUST-QUIZ": ["quizzes", "language-edge-cases"],
  "LIB-ALGORITHMS": ["algorithms", "code-reading"],
  "LIB-EXERCISM": ["exercises", "mentoring"],
};

/** @type {LibraryEntry[]} */
export const referenceLibraries = [
  ...coreLibraries.map((entry) => ({ ...entry, topics: coreTopics[entry.id] ?? [] })),
  ...extendedLibraries,
];

const libraryById = new Map(referenceLibraries.map((entry) => [entry.id, entry]));

/**
 * Chapter-scoped further reading. Each row is
 * [libraryId, section title, deep link, locally authored reason to read it now].
 */
const chapterReading = {
  1: [
    [
      "LIB-RBE",
      "Hello World",
      "https://doc.rust-lang.org/rust-by-example/hello.html",
      "The same first program with every line annotated.",
    ],
    [
      "LIB-CARGO",
      "Why Cargo Exists",
      "https://doc.rust-lang.org/cargo/guide/why-cargo-exists.html",
      "Explains what cargo new actually buys you before you build habits around it.",
    ],
    [
      "LIB-COMPREHENSIVE",
      "Welcome to Comprehensive Rust",
      "https://google.github.io/comprehensive-rust/",
      "A second, faster on-ramp if the Book's pace feels slow.",
    ],
  ],
  2: [
    [
      "LIB-RBE",
      "Standard Library Types",
      "https://doc.rust-lang.org/rust-by-example/std.html",
      "The types the guessing game leans on, isolated one at a time.",
    ],
    [
      "LIB-STD",
      "std::io::stdin",
      "https://doc.rust-lang.org/std/io/fn.stdin.html",
      "Read the actual signature you are calling instead of copying the call.",
    ],
    [
      "LIB-CARGO",
      "Dependencies",
      "https://doc.rust-lang.org/cargo/guide/dependencies.html",
      "What adding rand to Cargo.toml commits you to.",
    ],
  ],
  3: [
    [
      "LIB-RBE",
      "Primitives",
      "https://doc.rust-lang.org/rust-by-example/primitives.html",
      "Integer, float, and tuple behaviour with runnable edge cases.",
    ],
    [
      "LIB-REFERENCE",
      "Expressions",
      "https://doc.rust-lang.org/reference/expressions.html",
      "The rule that makes if and match expressions rather than statements.",
    ],
    [
      "LIB-RUSTLINGS",
      "variables & functions",
      "https://github.com/rust-lang/rustlings",
      "Extra repetitions on exactly these constructs, compiler-first.",
    ],
  ],
  4: [
    [
      "LIB-RBE",
      "Scoping rules",
      "https://doc.rust-lang.org/rust-by-example/scope.html",
      "RAII, moves, borrows, and lifetimes shown as short programs.",
    ],
    [
      "LIB-ERROR-INDEX",
      "E0382: use of moved value",
      "https://doc.rust-lang.org/error_codes/E0382.html",
      "The error you will meet most this chapter, with its minimal repro.",
    ],
    [
      "LIB-COMPREHENSIVE",
      "Memory Management",
      "https://google.github.io/comprehensive-rust/memory-management.html",
      "Stack/heap diagrams that make the move rule concrete.",
    ],
    [
      "LIB-NOMICON",
      "Ownership and Lifetimes",
      "https://doc.rust-lang.org/nomicon/ownership.html",
      "Stretch reading: why the rule exists, stated as an aliasing invariant.",
    ],
  ],
  5: [
    [
      "LIB-RBE",
      "Structures",
      "https://doc.rust-lang.org/rust-by-example/custom_types/structs.html",
      "Tuple, unit, and named structs side by side.",
    ],
    [
      "LIB-API-GUIDELINES",
      "Naming",
      "https://rust-lang.github.io/api-guidelines/naming.html",
      "Name constructors and accessors the way the ecosystem expects from day one.",
    ],
    [
      "LIB-STD",
      "Derivable traits",
      "https://doc.rust-lang.org/std/index.html#primitives",
      "What each #[derive] actually generates and requires.",
    ],
  ],
  6: [
    [
      "LIB-RBE",
      "Enums",
      "https://doc.rust-lang.org/rust-by-example/custom_types/enum.html",
      "Data-carrying variants and match ergonomics in small programs.",
    ],
    [
      "LIB-STD",
      "Option",
      "https://doc.rust-lang.org/std/option/enum.Option.html",
      "The combinator list is the real lesson; read it once end to end.",
    ],
    [
      "LIB-PATTERNS",
      "Idioms",
      "https://rust-unofficial.github.io/patterns/idioms/index.html",
      "How experienced Rust uses enums instead of booleans and flags.",
    ],
    [
      "LIB-EFFECTIVE",
      "Item 1: Use the type system to express your data structures",
      "https://effective-rust.com/use-types.html",
      "Why an enum beats a bool plus a comment, argued in production terms.",
    ],
  ],
  7: [
    [
      "LIB-RBE",
      "Modules",
      "https://doc.rust-lang.org/rust-by-example/mod.html",
      "Visibility and paths demonstrated rather than described.",
    ],
    [
      "LIB-CARGO",
      "Package Layout",
      "https://doc.rust-lang.org/cargo/guide/project-layout.html",
      "The conventional directory shape Cargo assumes without being told.",
    ],
    [
      "LIB-API-GUIDELINES",
      "Future proofing",
      "https://rust-lang.github.io/api-guidelines/future-proofing.html",
      "Why pub is a commitment, not a convenience.",
    ],
  ],
  8: [
    [
      "LIB-STD",
      "std::collections",
      "https://doc.rust-lang.org/std/collections/index.html",
      "The selection guide at the top of this page is the whole chapter, compressed.",
    ],
    [
      "LIB-RBE",
      "Vectors",
      "https://doc.rust-lang.org/rust-by-example/std/vec.html",
      "Growth, indexing, and iteration with runnable examples.",
    ],
    [
      "LIB-PERF",
      "Collections",
      "https://nnethercote.github.io/perf-book/collections.html",
      "The allocation costs behind the convenience.",
    ],
  ],
  9: [
    [
      "LIB-RBE",
      "Error handling",
      "https://doc.rust-lang.org/rust-by-example/error.html",
      "panic, Option, Result, and ? built up in order.",
    ],
    [
      "LIB-ERROR-INDEX",
      "E0277: trait not satisfied",
      "https://doc.rust-lang.org/error_codes/E0277.html",
      "The error ? produces when your error types do not line up yet.",
    ],
    [
      "LIB-PATTERNS",
      "Anti-patterns: unwrap",
      "https://rust-unofficial.github.io/patterns/anti_patterns/index.html",
      "Where unwrap is fine and where it is a latent outage.",
    ],
    [
      "LIB-API-GUIDELINES",
      "Interoperability",
      "https://rust-lang.github.io/api-guidelines/interoperability.html",
      "Implement std::error::Error properly so callers can compose your failures.",
    ],
  ],
  10: [
    [
      "LIB-RBE",
      "Generics",
      "https://doc.rust-lang.org/rust-by-example/generics.html",
      "Bounds, where clauses, and associated items as short programs.",
    ],
    [
      "LIB-REFERENCE",
      "Lifetime elision",
      "https://doc.rust-lang.org/reference/lifetime-elision.html",
      "The exact three rules the compiler applies before it asks you for annotations.",
    ],
    [
      "LIB-ERROR-INDEX",
      "E0106: missing lifetime specifier",
      "https://doc.rust-lang.org/error_codes/E0106.html",
      "Read the repair pattern once and this error stops being mysterious.",
    ],
    [
      "LIB-NOMICON",
      "Subtyping and Variance",
      "https://doc.rust-lang.org/nomicon/subtyping.html",
      "Stretch reading for why some lifetime errors resist the obvious fix.",
    ],
  ],
  11: [
    [
      "LIB-RBE",
      "Testing",
      "https://doc.rust-lang.org/rust-by-example/testing.html",
      "Unit, integration, and doc tests with their directory conventions.",
    ],
    [
      "LIB-CARGO",
      "cargo test",
      "https://doc.rust-lang.org/cargo/commands/cargo-test.html",
      "Filters, --nocapture, and harness flags you will use constantly.",
    ],
    [
      "LIB-API-GUIDELINES",
      "Documentation",
      "https://rust-lang.github.io/api-guidelines/documentation.html",
      "Doc examples are tests; write them as evidence, not decoration.",
    ],
  ],
  12: [
    [
      "LIB-COOKBOOK",
      "Command line",
      "https://rust-lang-nursery.github.io/rust-cookbook/cli.html",
      "Argument parsing and ANSI output the way the ecosystem does it.",
    ],
    [
      "LIB-STD",
      "std::process::exit",
      "https://doc.rust-lang.org/std/process/fn.exit.html",
      "Exit codes are part of a CLI's contract with the shell.",
    ],
    [
      "LIB-PATTERNS",
      "Structuring a CLI",
      "https://rust-unofficial.github.io/patterns/patterns/index.html",
      "Separating parse, run, and report so the program stays testable.",
    ],
  ],
  13: [
    [
      "LIB-RBE",
      "Iterators",
      "https://doc.rust-lang.org/rust-by-example/trait/iter.html",
      "Implementing Iterator by hand before leaning on adapters.",
    ],
    [
      "LIB-STD",
      "Iterator",
      "https://doc.rust-lang.org/std/iter/trait.Iterator.html",
      "The full adapter and consumer list; laziness is stated per method.",
    ],
    [
      "LIB-PERF",
      "Iterators",
      "https://nnethercote.github.io/perf-book/iterators.html",
      "When an adapter chain is free and when it is not.",
    ],
    [
      "LIB-RUST-QUIZ",
      "Closure captures",
      "https://dtolnay.github.io/rust-quiz/",
      "Calibrate whether you actually predict capture modes correctly.",
    ],
  ],
  14: [
    [
      "LIB-CARGO",
      "Workspaces",
      "https://doc.rust-lang.org/cargo/reference/workspaces.html",
      "The multi-crate layout this tutor itself uses.",
    ],
    [
      "LIB-CARGO",
      "Features",
      "https://doc.rust-lang.org/cargo/reference/features.html",
      "Additive features and the unification rule that surprises everyone once.",
    ],
    [
      "LIB-API-GUIDELINES",
      "Necessities",
      "https://rust-lang.github.io/api-guidelines/necessities.html",
      "License, metadata, and docs.rs requirements before you publish anything.",
    ],
  ],
  15: [
    [
      "LIB-TOO-MANY-LISTS",
      "A Bad Stack",
      "https://rust-unofficial.github.io/too-many-lists/first.html",
      "The single best exercise for Box, Option, and ownership under pressure.",
    ],
    [
      "LIB-STD",
      "Rc",
      "https://doc.rust-lang.org/std/rc/struct.Rc.html",
      "Read the cycle warning and Weak section, not just the constructor.",
    ],
    [
      "LIB-NOMICON",
      "Drop Check",
      "https://doc.rust-lang.org/nomicon/dropck.html",
      "Why drop order is a type-system concern and not merely a convention.",
    ],
  ],
  16: [
    [
      "LIB-ATOMICS",
      "Basics of Rust Concurrency",
      "https://marabos.nl/atomics/basics.html",
      "Threads, scoped threads, and shared ownership stated precisely.",
    ],
    [
      "LIB-ATOMICS",
      "Memory Ordering",
      "https://marabos.nl/atomics/memory-ordering.html",
      "The chapter that turns 'use Ordering::SeqCst' into an actual decision.",
    ],
    [
      "LIB-STD",
      "Send and Sync",
      "https://doc.rust-lang.org/std/marker/trait.Send.html",
      "The two markers behind almost every concurrency compile error you will hit.",
    ],
    [
      "LIB-ERROR-INDEX",
      "E0373: closure may outlive",
      "https://doc.rust-lang.org/error_codes/E0373.html",
      "The spawn error, and why move is the honest fix.",
    ],
  ],
  17: [
    [
      "LIB-ASYNC",
      "Under the Hood: Executing Futures",
      "https://rust-lang.github.io/async-book/02_execution/01_chapter.html",
      "Build the mental model of poll and wake before using any runtime.",
    ],
    [
      "LIB-TOKIO",
      "Shared state",
      "https://tokio.rs/tokio/tutorial/shared-state",
      "How async and locks interact once tasks outlive a single scope.",
    ],
    [
      "LIB-TOKIO",
      "Graceful shutdown",
      "https://tokio.rs/tokio/tutorial/graceful-shutdown",
      "Cancellation is a design decision; this shows the standard shape.",
    ],
    [
      "LIB-STD",
      "std::future::Future",
      "https://doc.rust-lang.org/std/future/trait.Future.html",
      "The whole trait is four lines; read them once and async demystifies.",
    ],
  ],
  18: [
    [
      "LIB-PATTERNS",
      "Newtype",
      "https://rust-unofficial.github.io/patterns/patterns/behavioural/newtype.html",
      "The Rust answer to a class hierarchy you were about to reach for.",
    ],
    [
      "LIB-REFERENCE",
      "Trait objects",
      "https://doc.rust-lang.org/reference/types/trait-object.html",
      "Object safety stated as rules rather than as compiler complaints.",
    ],
    [
      "LIB-ERROR-INDEX",
      "E0038: not object safe",
      "https://doc.rust-lang.org/error_codes/E0038.html",
      "Exactly which trait shapes cannot become dyn Trait.",
    ],
  ],
  19: [
    [
      "LIB-REFERENCE",
      "Patterns",
      "https://doc.rust-lang.org/reference/patterns.html",
      "The complete pattern grammar, including the forms the Book skips.",
    ],
    [
      "LIB-RBE",
      "match",
      "https://doc.rust-lang.org/rust-by-example/flow_control/match.html",
      "Guards, bindings, and destructuring as runnable examples.",
    ],
    [
      "LIB-RUST-QUIZ",
      "Pattern binding modes",
      "https://dtolnay.github.io/rust-quiz/",
      "Match ergonomics are where confident readers still get it wrong.",
    ],
  ],
  20: [
    [
      "LIB-MACROS",
      "macro_rules!",
      "https://veykril.github.io/tlborm/decl-macros.html",
      "Fragment specifiers, repetition, and hygiene done properly.",
    ],
    [
      "LIB-NOMICON",
      "Meet Safe and Unsafe",
      "https://doc.rust-lang.org/nomicon/meet-safe-and-unsafe.html",
      "What unsafe actually turns off, which is less than most people assume.",
    ],
    [
      "LIB-REFERENCE",
      "Type coercions",
      "https://doc.rust-lang.org/reference/type-coercions.html",
      "Deref coercion and the other implicit conversions behind 'advanced' errors.",
    ],
    [
      "LIB-ERROR-INDEX",
      "E0133: unsafe operation",
      "https://doc.rust-lang.org/error_codes/E0133.html",
      "The obligation you take on the moment you write unsafe.",
    ],
  ],
  21: [
    [
      "LIB-TOO-MANY-LISTS",
      "An Ok Unsafe Queue",
      "https://rust-unofficial.github.io/too-many-lists/fifth.html",
      "A capstone in reasoning about aliasing while something still has to work.",
    ],
    [
      "LIB-PERF",
      "Profiling",
      "https://nnethercote.github.io/perf-book/profiling.html",
      "Measure the server before tuning the thread pool.",
    ],
    [
      "LIB-TOKIO",
      "Tokio tutorial",
      "https://tokio.rs/tokio/tutorial",
      "The async counterpart to the Book's thread-pool server.",
    ],
  ],
};

/** Always-available companions, appended to every lesson. */
const standingReading = [
  [
    "LIB-BOOK",
    "The Rust Programming Language",
    "https://doc.rust-lang.org/book/",
    "The long-form chapter this lesson compresses.",
  ],
  [
    "LIB-ERROR-INDEX",
    "The rustc Error Index",
    "https://doc.rust-lang.org/error_codes/",
    "Look up any E-code the terminal prints instead of guessing at it.",
  ],
];

/**
 * Further reading for a Book chapter, resolved against the library catalog.
 * @param {number} chapter
 */
export function furtherReadingFor(chapter) {
  const rows = [...(chapterReading[chapter] ?? []), ...standingReading];
  const seen = new Set();
  const readings = [];
  for (const [libraryId, title, url, why] of rows) {
    const entry = libraryById.get(libraryId);
    if (!entry || seen.has(url)) continue;
    seen.add(url);
    readings.push({
      libraryId,
      library: entry.title,
      title,
      url,
      why,
      license: entry.license,
      level: entry.level,
    });
  }
  return readings;
}

export function libraryCatalog() {
  return referenceLibraries.map((entry) => ({ ...entry }));
}
